# Schema for the configuration files of the Joinup user module.
joinup_user.mail:
 type: config_object
 label: 'Email settings'
 mapping:
  email_admin_update:
    type: mail
    label: 'Account updated by administrator confirmation'
