sparql_entity_storage.mapping.*.third_party.rdf_schema_field_validation:
  type: mapping
  label: 'Settings related to the fields defined in a schema.'
  mapping:
    property_predicates:
      type: sequence
      label: 'The property predicates that define the relationship.'
      sequence:
        type: string
        label: 'A property predicate'
    graph:
      type: string
      label: 'The graph that stores the schema definition.'
    class:
      type: string
      label: 'The SPARQL Uri that defines a class object.'
